export declare const Commands: {
    "--message": "--message";
    "--out-dir": "--out-dir";
    "--file": "--file";
    "--namespace": "--namespace";
    "--beat": "--beat";
    "--html": "--html";
    "--webui": "--webui";
    "--open-browser": "--open-browser";
    "--graphiql-playground": "--graphiql-playground";
    "--node-only": "--node-only";
    "--silent": "--silent";
    "--unminify": "--unminify";
    "--browser": "--browser";
    "--v": "--v";
    "--tsconfig": "--tsconfig";
    "--verbose": "--verbose";
    "--default-ipfs-node": "--default-ipfs-node";
    "--deployer-config-name": "--deployer-config-name";
    "--graphiql": "--graphiql";
    "--open-browser-graphiql": "--open-browser-graphiql";
    "--server-watcher": "--server-watcher";
    "--server-watcher-port": "--server-watcher-port";
    "--graphiql-subscription-endpoint": "--graphiql-subscription-endpoint";
    "--graphiql-auth-token": "--graphiql-auth-token";
    "--graphql-endpoint": "--graphql-endpoint";
    "--write-effects": "--write-effects";
    "--graphiql-endpoint": "--graphiql-endpoint";
    "--graphql-api-port": "--graphql-api-port";
    "--disable-package-collection": "--disable-package-collection";
    "--collect-packages": "--collect-packages";
    "--help": "--help";
};
export declare type Commands = keyof typeof Commands;
export declare const ExcludedFromHelpers: {
    "--v": "--v";
};
export declare type ExcludedFromHelpers = keyof typeof ExcludedFromHelpers;
