version: '2'
services:

  rxdi-ipfs-deployer:
    image: rxdi/deployer:latest
    restart: always
    mem_limit: 1000000000
    cpu_shares: 73
    container_name: rxdi-ipfs-deployer
    environment:
      - API_PORT=9300
      - RANDOM_PORT=false
      - IPFS_API_GATEWAY=/ip4/127.0.0.1/tcp/8080
      - IPFS_API_PORT=/ip4/127.0.0.1/tcp/5001
    ports:
      - "9300:9300"
      - "5001:5001"
      - "8080:8080"
      - "8957:8957"
    volumes:
      - ./packages:/usr/src/app/packages
      - ./.rxdi:/root/.rxdi
      - ./.jsipfs:/root/.jsipfs