import { __DEPLOYER_OUTPUT_CONFIG_NAME, HistoryModel } from '../../../env.injection.tokens';
import { BootstrapLogger, PluginInterface } from '@rxdi/core';
import { FileUserService } from '../../services/file/file-user.service';
import { IPFSFile } from '@gapi/ipfs';
import { ParcelBundlerService } from '../../services/parcel-bundler/parcel-bundler.service';
import { FileIpfsService } from '../../services/ipfs-file/ipfs-file.service';
import { FileService } from '../../services/file/file.service';
import { TypescriptDefinitionGeneratorService } from '../../services/dts-generator/dts-generator.service';
import { TsConfigGenratorService } from '../../services/tsconfig-generator/tsconfig-generator.service';
import { TableService } from '../../services/table-service/table-service';
import { BuildHistoryService } from '../../services/build-history/build-history.service';
import { PreviwsService } from '../../services/previews/previews.service';
import { ErrorReasonService } from '../../services/error-reason/error-reason.service';
import { StatusService } from '../../status/status.service';
export declare class CompilePlugin implements PluginInterface {
    private parcelBundler;
    private logger;
    private ipfsFile;
    private fileService;
    private fileUserService;
    private typingsGenerator;
    private tsConfigGenerator;
    private tableService;
    private buildHistoryService;
    private previwsService;
    private errorReasonService;
    private statusService;
    private fileName;
    private folder;
    private resolutionTime;
    private outputConfigName;
    private namespace;
    private commitMessage;
    private extension;
    constructor(parcelBundler: ParcelBundlerService, logger: BootstrapLogger, ipfsFile: FileIpfsService, fileService: FileService, fileUserService: FileUserService, typingsGenerator: TypescriptDefinitionGeneratorService, tsConfigGenerator: TsConfigGenratorService, tableService: TableService, buildHistoryService: BuildHistoryService, previwsService: PreviwsService, errorReasonService: ErrorReasonService, statusService: StatusService);
    register(): Promise<{}>;
    isJavascriptCompilation(): boolean;
    compile(): Promise<import("rxjs/internal/Subscription").Subscription>;
    completeBuildAndAddToIpfs(folder: string, file: string, message: any, namespace: string, outputConfigName: __DEPLOYER_OUTPUT_CONFIG_NAME): import("rxjs/internal/Observable").Observable<{}>;
    fileNotAddedToIpfs(file: IPFSFile[]): void;
    integrityCheck(dag: HistoryModel, file: IPFSFile[], typings: IPFSFile[]): void;
    showError(hash: string): void;
    writeOtherFile(file: any): import("rxjs/internal/Observable").Observable<IPFSFile[]>;
    logSuccess(res: any): void;
    completeBuildAndAddToIpfs2(namespace?: string): import("rxjs/internal/Observable").Observable<IPFSFile[]>;
}
